version = 1

[toml]

[json]
version_raw = "https://raw.githubusercontent.com/Jaysonjson/PSEMod/master/versions.json"
resourcepack_raw = "https://raw.githubusercontent.com/Jaysonjson/PSEMod/master/resourcepack.json"
[1.13.2]
  description = "DESC"
